# Generated by Django 6.0.6 on 2026-07-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=200)),
                ('code', models.CharField(help_text='Course code', max_length=50)),
                ('section', models.CharField(help_text='Course section', max_length=50)),
                ('period', models.CharField(help_text='Academic period (e.g., 2026-1)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='evaluations.course')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='evaluations.course')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('general_comment', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.group')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(help_text='e.g., 1A, 2B', max_length=10)),
                ('description', models.TextField()),
                ('weight', models.FloatField(help_text='Weight as a decimal (e.g., 0.10 for 10%)')),
                ('item_type', models.CharField(choices=[('GROUP', 'Group'), ('INDIVIDUAL', 'Individual')], default='GROUP', max_length=15)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.rubric')),
            ],
            options={
                'ordering': ['item_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='e.g., MB, B, S', max_length=50)),
                ('score_percentage', models.FloatField(help_text='Value out of 100')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='evaluations.rubric')),
            ],
            options={
                'ordering': ['-score_percentage'],
            },
        ),
        migrations.CreateModel(
            name='GroupItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_scores', to='evaluations.evaluation')),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.rubricitem')),
                ('level_achieved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.rubriclevel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Student ID (RUT, DNI, etc.)', max_length=50, unique=True)),
                ('first_names', models.CharField(max_length=100)),
                ('last_name_1', models.CharField(max_length=100)),
                ('last_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.ManyToManyField(related_name='students', to='evaluations.course')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_scores', to='evaluations.evaluation')),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.rubricitem')),
                ('level_achieved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.rubriclevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='student_groups', to='evaluations.student'),
        ),
    ]
