# Generated by Django 6.0.6 on 2026-07-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_remove_evaluation_rubric_evaluation_direct_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Detailed descriptor for this level and item', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='evaluations.rubricitem')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='evaluations.rubriclevel')),
            ],
            options={
                'unique_together': {('item', 'level')},
            },
        ),
    ]
