# Generated by Django 6.0.6 on 2026-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_evaluation_evaluated_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassessment',
            options={'ordering': ['assessment_type', 'id']},
        ),
        migrations.AddField(
            model_name='course',
            name='exam_weight',
            field=models.FloatField(default=30.0, help_text='Weight of the exam grade (e.g., 30 for 30%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='exemption_grade',
            field=models.FloatField(blank=True, default=5.5, help_text='Grade required to be exempted from the exam (e.g., 5.5). Leave blank if exam is mandatory.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='presentation_weight',
            field=models.FloatField(default=70.0, help_text='Weight of the presentation grade (e.g., 70 for 70%)'),
        ),
        migrations.AddField(
            model_name='courseassessment',
            name='assessment_type',
            field=models.CharField(choices=[('PRESENTATION', 'Presentation'), ('EXAM', 'Exam')], default='PRESENTATION', max_length=20),
        ),
    ]
